### PR TITLE
Homogeneity tests

### PR DESCRIPTION
**Pull request by victor-moreno**
Hi Jonathon
I have added the F ratio test to t-test and the Bartlett test to ANOVA/ANCOVA
I have not formatted properly the code so you can better see the differences. If you like it I will reformat the code indenting several IFs

Also, in a second round, I will add everything to the Oneway ANOVA.

I had to copy several private functions because residuals in the parent were standardized and Levene's used the raw ones from the model. The differences were minor, but I wanted the new results for Levene exactly the same as before.

### CODE REVIEW

**Comment by jonathon-love** [comment]
looks good to me!

**Comment by victor-moreno** [comment]
Hi Jonathon,
I have revised the code for the Bartlett test, in ANOVA, I was using the formula with residuals from Levene's. Now I think is correct. 
Also, I have added the extra tests to one-way ANOVA. The normality tests were not in linear regression, so I have deleted that from description. It can be added easily if you think it is worth.

Please test the result against some datasets you have the right output, I don't have SPSS or SAS. I have checked against one old Spanish statistical software and get the same results.

**Comment by jonathon-love** [comment]
i've pushed it to the library. if you were feeling altruistic, i'd love to see these added to lin reg as well (it's a little more work, because there's multiple models involved in the lin reg)

cheers

jonathon

**Comment by victor-moreno** [comment]
Hi Jonathon,
I will try to add the normality tests to lin reg, and I will revise if it makes sense a test for homogeneity of variances to advise the use of more sophisticated regression models. 
Victor

**Comment by jonathon-love** [comment]
awesome ... not sure if you're interested in doing KS and AD too :P

**Pull request merged**
